Homework 4
mennekis/nodejs24_hw_Nikolayenko pull request #4
Opened 2024-02-09 20:15 UTC by mennekis

2024-02-10 11:07 UTC, evhenious commented on utils/logger.js
> +               .map(JSON.stringify)
Чому різні способи підготовки месаджів для файлу? Тут в тебе бачу `JSON.stringify`, а в `info` та `warn` немає - хоча всі три методи можуть отримувати не тільки строкові аргументи...
Якщо я зараз у тебе передам в метод `info` об'єкт, в лог файлі буде такеЖ
```
2024-02-10T11:03:47.813Z [INFO] main: [object Object]
```

Це не є коректно, зроби будь ласка для всіх методів те що зробив у `warn`

2024-02-10 11:09 UTC, evhenious requested changes
Поправ будь ласка вивід в файл (те що я відкоментав в логгері)

2024-02-11 13:19 UTC, mennekis commented on utils/logger.js
> +               .map(JSON.stringify)
Привет! Ну у меня в коде только это вылезло)) показало при warn Обджект-обджет))) вот только к нему и применил. Спасибо поправил

2024-02-11 13:20 UTC, mennekis commented
Привет! Спасибо, поправил.

2024-02-12 15:45 UTC, merged